---
title: "Prevalence model in JAGS"
author: "Dylan Simpson"
date: "April 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(R2jags)
library(lme4)
library(AICcmodavg)
library(lattice)
source("plotPost.R")
source("HDIofMCMC.R")
```

```{r Simulating data}
set.seed(10)

#Set up long-form data, where each of 12 sites have 10 plots, and each plot is sampled 4 times

site <- rep(1:12, each = 40) # site ID

plot <- rep(rep(1:10, each = 4), 12) # within-site plot ID

obs <- rep(1:4, 120) # within-plot sample ID

year <- rep(1:4, each = 480) # Year ID

N <- length(year) # total number of samples

n <- rpois(N, 5) # number of ticks collected during each observation

# plot-level observations of covariates
x1 <- rep( # outer repeats operation across four years
  rep(rnorm(120), each = 4) # inner repeat each measurement at the plot level within a year
  ,4) 

x2 <- rep(
  rep(rnorm(120), each = 4)
  ,4)

mu <- -2 # grand mean
sigma_0 <- 1 # variance around the mean associated with sites
sigma_k <- rep(runif(12, .2, .6), each = 10) # variance around site-means associated with plots
beta1 <- .7
beta2 <- -.4

alpha <- rep(rnorm(12, mu, sigma_0), each = 10) # draws to establish true values of site-level intercepts
beta0 <- rep(rnorm(120, alpha, sigma_k), # draws establish true values of plot-level intercepts, 
             each = 4, times = 4)        # repeated for each of four years (beta0 is equal across years)

pi_kit <- plogis(beta0 + beta1*x1 + beta2*x2)
piStar_kit <- 1 - (1-pi_kit)^n

y <- rbinom(N, 1, prob = piStar_kit)

dat <- data.frame(rep(site,4), rep(plot,4), rep(obs,4), year, y, n, x1, x2)
colnames(dat)[1:3] <- c("site", 'plot', 'obs')
```

```{r GLMMs}
### Modeling via GLMM:

fm1 <- glmer(y ~ x1 + (1|site/plot), data = dat, family = 'binomial')
fm2 <- glmer(y ~ x2 + (1|site/plot), data = dat, family = 'binomial')
fm3 <- glmer(y ~ x1 + x2 + (1|site/plot), data = dat, family = 'binomial')
fm4 <- glmer(y ~ x1 + x2 + n + (1|site/plot), data = dat, family = 'binomial')

aictab(list(fm1, fm2, fm3, fm4))

summary(fm1)
summary(fm2)
summary(fm3)
summary(fm4)

## This can be cool, but is time consuming:
# fm4.profile <- profile(fm4)
# xyplot(fm4.profile)
```

```{r JAGS prep}
### format data into arrays for logical indexing:
y <- xtabs(y ~ site + plot + obs + year, data = dat)
n <- xtabs(n ~ site + plot + obs + year, data = dat)
x1 <- xtabs(x1 ~ site + plot + year, data = dat[dat$obs==1,])
x2 <- xtabs(x2 ~ site + plot + year, data = dat[dat$obs==1,])

### Create data list:
dataList <- list(
  y = y,
  x1 = x1,
  x2 = x2,
  nsite = dim(y)[1],
  nplot = dim(y)[2],
  nobs = dim(y)[3],
  nyear = dim(y)[4],
  n = n
)
```

```{r Defining the model}
prevalence <- function(){
  # Likelihood:
  for(k in 1:nsite){
    for(i in 1:nplot){
      for(t in 1:nyear){
        for(j in 1:nobs){
          y[k,i,j,t] ~ dbern(1-(1-pi[k,i,t])^n[k,i,j,t])
        }
        pi[k,i,t] <- ilogit(beta0[k,i] + beta1*x1[k,i,t] + beta2*x2[k,i,t])
      }
      beta0[k,i] ~ dnorm(alpha[k], 1/sigma[k]^2)
    }
    alpha[k] ~ dnorm(mu, 1/sigma0^2)
  }
  
  # Priors:
  beta1 ~ dnorm(0, .01)
  beta2 ~ dnorm(0, .01)
  mu ~ dnorm(0, .01)
  sigma0 ~ dunif(0,10)
  for(k in 1:nsite){
    sigma[k] ~ dunif(1,10)
  }
}
```

```{r JAGS set up}
### Define initial values
    # Note: This model seems very sensitive to initial values, and won't run if they are too big
inits1 <- list(
    beta1 = 0,
    beta2 = 0,
    mu = 0,
    sigma = rep(1, length(unique(site))),
    sigma0 = 1
  )
inits2 <- list(
    beta1 = .1,
    beta2 = .1,
    mu = -1,
    sigma = rep(.6, length(unique(site))),
    sigma0 = .6
  )

inits3 <- list(
    beta1 = .5,
    beta2 = -.5,
    mu = -2,
    sigma = rep(.3, length(unique(site))),
    sigma0 = .3
  )
inits <- list(inits1, inits2, inits3)

params <- c('beta1', 'beta2', 'mu', 'sigma', 'sigma0')
```

```{r Run model}
prevMod <- jags(data = dataList, 
                # inits = inits, 
                parameters.to.save = params, 
                model.file = prevalence, 
                n.chains = 1, 
                n.iter = 12000, 
                n.burnin = 2000,
                n.thin = 10)

prevMod.mcmc <- as.mcmc(prevMod) # save as coda object, req'd for useful functions
prevMat <- as.matrix(prevMod.mcmc) # convert to matrix and data frame for plotting
modDat <- data.frame(prevMat)
```

```{r JAGS diagnostics}
traceplot(prevMod.mcmc)
# gelman.diag(prevMod.mcmc)
```

```{r Results}
plotPost(modDat$mu, xlab = 'b0')
plotPost(modDat$beta1, xlab = 'b1')
plotPost(modDat$beta2, xlab = 'b2')
plotPost(modDat$sigma0, xlab = 'sigma0')

# plotPost(modDat$sigma.1., xlab = 'sigma, k = 1')
# plotPost(modDat$sigma.2., xlab = 'sigma, k = 2')
# plotPost(modDat$sigma.3., xlab = 'sigma, k = 3')
# plotPost(modDat$sigma.4., xlab = 'sigma, k = 4')
# plotPost(modDat$sigma.5., xlab = 'sigma, k = 5')
# plotPost(modDat$sigma.6., xlab = 'sigma, k = 6')
# plotPost(modDat$sigma.7., xlab = 'sigma, k = 7')
# plotPost(modDat$sigma.8., xlab = 'sigma, k = 8')
# plotPost(modDat$sigma.9., xlab = 'sigma, k = 9')
# plotPost(modDat$sigma.10., xlab = 'sigma, k = 10')
# plotPost(modDat$sigma.11., xlab = 'sigma, k = 11')
# plotPost(modDat$sigma.12., xlab = 'sigma, k = 12')
```

```{r True values}
mu
sigma_0
unique(sigma_k)
beta1
beta2
```